### ISSUE TITLE
Migrate Gitter to stylus/stylus

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus-lang.com#15]
Stylus has a problem with fragmentation. I think it's fine to honor the patron of the language, but not at the cost of fragmenting the brand.

Perhaps we should migrate the Gitter to `stylus/stylus`, and add some buttons to that chat room on the main repo's README (as well as some other sweeeeeet badges) and on the website itself.

We should really try to migrate users to the same official-looking chat room in whatever ways we can.

**Comment by iChenLei** [comment]
Now we can use [Stylus Github Discussions](https://github.com/stylus/stylus/discussions). 🎉
