### ISSUE TITLE
Try Stylus not compiling valid code

### ISSUE THREAD

**Issue by coreyworrell** [stylus/stylus-lang.com#18]
I notice that sometimes the http://stylus-lang.com/try.html page does not compile correctly. I use it quite often to test how things will work or look (probably better to do locally, but it makes it easy to isolate and test code).

Example:
```stylus
// Mixin
position(type, values...)
    properties = top right bottom left
    skip       = _

    // top value
    push(values, skip) if length(values) is 0

    // right value
    push(values, values[0]) if length(values) is 1

    // bottom value
    push(values, values[0]) if length(values) is 2

    // left value
    push(values, values[1]) if length(values) is 3

    position: type

    for property, index in properties
        {property}: values[index] if values[index] isnt skip

// Usage
.vh
.screen-reader-text
    position: absolute auto _ _ -999em
    width: 1px
    height: 1px
    overflow: hidden
```

[Try Stylus!](http://stylus-lang.com/try.html#?code=%2F%2F%20Mixin%0Aposition(type%2C%20values...)%0A%20%20%20%20properties%20%3D%20top%20right%20bottom%20left%0A%20%20%20%20skip%20%20%20%20%20%20%20%3D%20_%0A%0A%20%20%20%20%2F%2F%20top%20value%0A%20%20%20%20push(values%2C%20skip)%20if%20length(values)%20is%200%0A%0A%20%20%20%20%2F%2F%20right%20value%0A%20%20%20%20push(values%2C%20values%5B0%5D)%20if%20length(values)%20is%201%0A%0A%20%20%20%20%2F%2F%20bottom%20value%0A%20%20%20%20push(values%2C%20values%5B0%5D)%20if%20length(values)%20is%202%0A%0A%20%20%20%20%2F%2F%20left%20value%0A%20%20%20%20push(values%2C%20values%5B1%5D)%20if%20length(values)%20is%203%0A%0A%20%20%20%20position%3A%20type%0A%0A%20%20%20%20for%20property%2C%20index%20in%20properties%0A%20%20%20%20%20%20%20%20%7Bproperty%7D%3A%20values%5Bindex%5D%20if%20values%5Bindex%5D%20isnt%20skip%0A%0A%2F%2F%20Usage%0A.vh%0A.screen-reader-text%0A%20%20%20%20position%3A%20absolute%20auto%20_%20_%20-999em%0A%20%20%20%20width%3A%201px%0A%20%20%20%20height%3A%201px%0A%20%20%20%20overflow%3A%20hidden)

It compiles just fine locally and on [CodePen](http://codepen.io/coreyworrell/pen/JEWbNz) though (view compiled CSS)

**Comment by kizu** [comment]
It seems that if there was an issue, it was fixed in one of the releases (right now both try.html and codepen render the same thing properly)
