### ISSUE TITLE
sec vuln

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus-lang.com#21]
![image](https://user-images.githubusercontent.com/224636/33357745-2f7a39a4-d492-11e7-83b8-73a33727a6b1.png)

**Comment by corysimmons** [comment]
@kizu @Panya

**Comment by kizu** [comment]
I think we can't be affected by it in any case, as the site is hosted as a static one, and that's just from the `gemfile.lock` which we could probably delete from the repo I guess?

**Comment by corysimmons** [comment]
I'd assume since we're static there is no worry, but I suspect gh-pages might run a `bundle` to end up with that .lock file regardless so doubt simply deleting it is a fix.

Maybe simply updating... 2 secs...

**Comment by corysimmons** [comment]
@kizu You care to pull https://github.com/stylus/stylus-lang.com/tree/cs/fixing-security-vuln and try `bundle exec jekyll serve --watch --config _config.yml,_config-dev.yml`?

I'm getting errors about Tenkan (which I think is one of your personal pkg's so you'd probably be able to identify the issue much faster than me).
