### ISSUE TITLE
Overwriting variables in media queries

### ISSUE THREAD

**Issue by Aran-Fey** [stylus/stylus-lang.com#24]
It seems that conditional overwriting of stylus variables with media queries isn't possible. For example, the following stylus code:

```stylus
bg_color = white

@media (prefers-color-theme: dark)
    bg_color = black

body
    background: bg_color
```

Compiles to:
```css
body {
  background: #fff;
}
```

Is this behavior intended? The documentation doesn't go into detail about how variables interact with media queries.

**Comment by svub** [comment]
Was working on this issue and just realized this considered normal and not a bug. It's something so useful to do good responsive design, didn't expect stylus to *not* have this feature.

FYI: define certain aspects as vars, overwrite those vars in certain breakpoints and then just use this vars in the style sheet. Very clean.

**Comment by iChenLei** [comment]
This behavior is normal and not bug, Media Query effective at runtime not compile time.
