### ISSUE TITLE
Domain renewal

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus-lang.com#25]
Hey I just noticed in my spam folder that the domain is up for renewal tomorrow. I'm broke and don't really think it's worth it anyway. Maybe we should just put it on stylus.github.io or something?

**Comment by Soitora** [comment]
Wish I could help with the payment but I'm in a similiar situation. If no one can chip in those $10 then I think Github Pages is fine

**Comment by natevw** [comment]
+1 to eventually just hosting it more simply, but sent @corysimmons an email re. a potential short-term option.

**Comment by corysimmons** [comment]
Hey yo Nathan reached out via email and offered to cover the $15 Hover charge so I went ahead and paid it. It looks up to me.

**Comment by corysimmons** [comment]
Domain back up. https enabled. Added @natevw to [README](https://github.com/stylus/stylus-lang.com#thanks). Thanks Nathan.

**Comment by natevw** [comment]
Glad to help!

**Comment by corysimmons** [comment]
@natevw Renewal coming up. Still interested in the domain? I can transfer it to you if you'd like?

**Comment by futekov** [comment]
I'll gladly take care of the site if you can't (don't want to) anymore.

**Comment by corysimmons** [comment]
@kizu @Panya You okay with adding @futekov to the org and letting him take over the design/maintenance of the site (it could use some mobile love—my version should've had a hamburger menu instead of whatever I was thinking)?

If so, I can transfer the domain to him as well.

tbh I don't use Stylus anymore.

**Comment by kizu** [comment]
Done, I remember @futekov from the great fork on https://csspre.com/, so would happy to have him take care of thew site!

![image](https://user-images.githubusercontent.com/177485/104893051-3b8adf00-5973-11eb-876a-dbb10223e0f0.png)

**Comment by natevw** [comment]
Thanks @futekov! Maybe it makes sense to have the domain start redirecting to a gh-pages URL or similar if you don't plan to renew it for many more years?

**Comment by corysimmons** [comment]
^ that's actually a really good idea. Redirect stylus-lang.com to stylus.github.io or something, and then next year stop paying for the domain.

---

@futekov Unlocked the domain and emailed you the auth code. Let me know if you need anything else.

**Comment by futekov** [comment]
@natevw for now I think I'll keep it as a .com

If circumstances change I'll redirect it to gh-pages at least several months before domain expiry.
