### ISSUE TITLE
 stylus-lang.com is not available

### ISSUE THREAD

**Issue by mjecov** [stylus/stylus-lang.com#31]
Try to access the website but it looks like it is unavailable now

**Comment by devmade** [comment]
+1 Facing the same issue since I tried opening the docs since yesterday
![image](https://user-images.githubusercontent.com/30465670/116089346-60a09380-a6c0-11eb-996d-bd410ec19d2a.png)

**Comment by futekov** [comment]
Seems like a misconfiguration somewhere, but I'm not sure where, the domain was transferred just a few weeks ago. Looking into it...

**Comment by futekov** [comment]
Looked like a SSL issue, shouldn't happen anymore.

@jekov thanks for reporting
