### ISSUE TITLE
Logo status

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus-lang.com#4]
I've sent MojoTech an email about using the logo. They'll probably approve it at the beginning of next week. If they don't or it takes too long we can design a new logo for it in a few days.

**Comment by corysimmons** [comment]
@kizu I talked to MojoTech about use of the logo and they're excited about the new website but would like to talk to you on the phone about some presentational guidelines they have in mind. Would you be interested in doing this?

**Comment by kizu** [comment]
Well, Skype (I'm `kizmarh` at it) would be preferred over phone for me, if possible :) I would glad to talk, maybe friday or at the weekend.

**Comment by corysimmons** [comment]
Sounds good. I'm adding you now and I'll forward your information to their design lead.

**Comment by corysimmons** [comment]
@kizu He said anytime after 10am EST is good on Friday.

**Comment by corysimmons** [comment]
@kizu Sorry I forgot about the appointment. Care to reschedule? Their design lead is available any time Wed - Friday, after 1pm EST.

**Comment by kizu** [comment]
Yep, but I'm afraid not on this week — I'm ill and won't be able to speak, so the next one probably. I'll get in touch!

**Comment by corysimmons** [comment]
How does Monday of next week anytime after 1pm EST sound?

**Comment by corysimmons** [comment]
@kizu Bump

**Comment by corysimmons** [comment]
~~I'm just going to start presenting new logo alternatives instead of continuing to halt this insanely overdue project.~~

@kizu MojoTech has decided to release the logo. Does Automattic need something official from them for this or will the email where they said we can use it suffice?

**Comment by kizu** [comment]
Sorry for the delay :D

> Does Automattic need something official from them for this or will the email where they said we can use it suffice?

The email would suffice, of course :)

**Comment by corysimmons** [comment]
Pretty sure no one is going to get sued or anything as long as we're all humanoids in this ordeal. Closing this as super stale.
