### ISSUE TITLE
Optimize site for speed

### ISSUE THREAD

**Issue by futekov** [stylus/stylus-lang.com#5]
Currently we're loading the full jQuery lib and as far as I can see it's only for `plugins.js` and `main.js` which are short, simple, and can easily be rewritten in vanilla js with IE8 (or IE7?) support.

**Comment by corysimmons** [comment]
@futekov Feel free to rewrite without jQuery (although I've never really thought loading a cached version of jQuery was a big deal whatsoever).

**Comment by corysimmons** [comment]
I get your complaint now, but I think it's a bigger issue than just jQuery. I don't think I'm using Modernizr at all, and I'm pretty sure we can drop half-support for older browsers and get rid of respond.js, etc. as well, so I'm going to retitle this issue. In the meantime, it _is_ only ~30kb for all that garbage, but I definitely get your point.

@kizu @Panya What kind of browser support are we aiming at? Is IE9+ alright?

I'm also thinking about migrating this to Netlify for some performance perks like HTTP2/CDN. It'd still be built directly from this repo. It'd just be faster. Anyone mind?

**Comment by kizu** [comment]
IE9+ with usable fallback for others. Feel free to do the migration if it would be faster and would still build from the repo :)

**Comment by corysimmons** [comment]
Okay, thanks for the autonomy. I don't think we'll have any downtime. I'm pretty tired so I might put this off until tomorrow. 😴
