### ISSUE TITLE
Github icon links to LearnBoost/stylus instead of stylus/stylus

### ISSUE THREAD

**Issue by cspotcode** [stylus/stylus-lang.com#7]
Hi all, happy to write a patch but I wasn't sure of the current state of the website, which branch to use, etc, etc.  It looks to me like things are in a state of flux at the moment, what with three sites floating around:
http://stylus.github.io/stylus
http://LearnBoost.github.io/stylus
http://www.stylus-lang.com

**Comment by cspotcode** [comment]
Also the homepage's "head on over to Github" link goes to https://github.com instead of https://github.com/stylus/stylus

**Comment by kizu** [comment]
Right now the http://LearnBoost.github.io/stylus is the old official docs, the http://www.stylus-lang.com is the new site that is under development and http://stylus.github.io/stylus/ was there by mistake, deleted it.

When the http://www.stylus-lang.com would be in a stable state, we'd promote it as an official one, adding redirects from the old site on LearnBoost.

Also, fixed an icon at the new site to lead to the proper repo, thanks!
